### ISSUE TITLE
Cannot include attribute writers from a module

### ISSUE THREAD

**Issue by wesm-outreach** [mdub/clamp#78] opened 2017-11-08 04:16 UTC
## Expected Behavior
Can include an attribute writer, like I would be able to do in other ruby situations, and have clamp use that method

## Actual Behavior
Clamp doesn't see that the method exists at all, and it's never called

## Repro Steps

```Ruby
#! /usr/bin/env ruby

require "clamp"

module Foo
  def fooilicious=(thing)
    @my_att = thing
    @fooilicious = thing
  end
end

class Bar < Clamp::Command
  option %w(--foo), 'FOO[:THING]', 'A fooy thing',
  attribute_name: :fooilicious

  include Foo

  def execute
    puts "executing"
    puts @my_att
  end
end

Bar.run
```

## Workaround

```diff
#! /usr/bin/env ruby

require "clamp"

- module Foo
-  def fooilicious=(thing)
-    @fooilicious = thing
-  end
-end

class Bar < Clamp::Command
  option %w(--foo), 'FOO[:THING]', 'A fooy thing',
  attribute_name: :fooilicious

-  include Foo
+ def fooilicious=(thing)
+   @fooilicious = thing
+ end

  def execute
    puts "executing"
    puts @fooilicious
  end
end

Bar.run
```

This workaround is not ideal because I have several commands that have similar behavior and I don't want to have command inheritance.

**Comment by mdub** [comment] 2017-11-08 07:05
Hi Wes. 

As described in [Declaring options](https://github.com/mdub/clamp#declaring-options), the `.option` method 

> ... works a little like `attr_accessor`, defining reader and writer methods on the command class

In your example, the generated `Bar#fooilicious=` overrides the included `Foo#fooilicious=`.

There are a few ways around it. First, if you have several commands or sub-commands that should support the same option, you can declare the option itself in a module:

```ruby
module Foo

  extend Clamp::Option::Declaration

  option %w(--foo), 'FOO', 'A fooy thing', attribute_name: :fooilicious

  def fooilicious=(arg)
    @fooilicious = arg
  end

end

class Bar < Clamp::Command

  include Foo

  def execute
    puts "executing"
    puts @fooilicious
  end

end
```

If that doesn't suit, you can _remove_ the Clamp-generated method:

```ruby
module Foo

  def fooilicious=(arg)
    @fooilicious = arg
  end

end

class Bar < Clamp::Command

  option %w(--foo), 'FOO', 'A fooy thing', attribute_name: :fooilicious
  remove_method :fooilicious=

  include Foo

  def execute
    puts "executing"
    puts @fooilicious
  end

end
```

I'll close this, as it's not a bug in Clamp.

**Closed by mdub** 2017-11-08 07:05 UTC

**Comment by wesm-outreach** [comment] 2017-11-08 15:09
@mdub thanks!
